### PR TITLE
AutoOrient to automatically fix orientation of images based on EXIF orientation flag

### PR DESCRIPTION
**Pull request by LeoAdamek**
This PR adds a new func to the bimg.Image type `AutoOrient` which will perform the required processes to correct the orientation of the image based on the EXIF orientation flag.

### CODE REVIEW

**Comment by LeoAdamek** [comment]
@h2non Thanks for the feedback, didn't see this func because its not exported.

Agreed there may be some redundancy here, but would it not make sense for this feature to behave in the same way the other "convenience" methods?

Is your suggestion that there be an `AutoOrient bool` property on the `Options` struct which will run the `calculateRotationAndFlip` function from resize.go ?

-Leo

**Comment by h2non** [comment]
> Is your suggestion that there be an AutoOrient bool property on the Options struct which will run the calculateRotationAndFlip function from resize.go ?

The intended default behavior is to process images with auto orientation, unless you explicitly want to disable that behavior via:
https://github.com/h2non/bimg/blob/master/options.go#L201

I agree about exposing that capability as part of the public API. 
Perhaps we should simply converge both functions into a single one which is also exported.

**Comment by LeoAdamek** [comment]
In which case, would an `AutoOrient` function just pass an empty `Options{}` struct to resize and return that? 

My my use case, I need to have the image correctly oriented for later processing, including being able to get the dimensions with that orientation applied.

**Comment by h2non** [comment]
This should be already fixed by #183. Feature is now available in `bimg` +1.0.11

**Pull request closed without merging**
