### PR TITLE
Restructure transformations

### PR DESCRIPTION
**Pull request by aksdb**
A discussed a while ago, I refactored **a lot** of *bimg* to allow for (mostly) lossless transformations and cleanup the interface while at it. I also tackled a few technical debts and possible bugs when I encountered them. This includes my RGBA support from PR #351.

Sorry for this HUGE PR. I think it's worth it, though.

The API of *bimg* is untouched. So everything that worked before, still works. Under the hood this uses a new API though, that is also exposed: `ImageTransformation`. Let's take the example from the documentation:

```go
// read the raw data
buffer, err := bimg.Read("image.jpg")
if err != nil {
  fmt.Fprintln(os.Stderr, err)
  return
}

// decode the image and prepare our transformation chain
it, err := bimg.NewImageTransformation(buffer)
if err != nil {
  fmt.Fprintln(os.Stderr, err)
  return
}

// crop the image to a specific width
err = it.Crop(bimg.CropOptions{Width: 300})
if err != nil {
  fmt.Fprintln(os.Stderr, err)
  return
}

// then flip it
err = it.Rotate(bimg.RotateOptions{Flip: true})
if err != nil {
  fmt.Fprintln(os.Stderr, err)
  return
}

// encode the image
newImage, err := it.Save(bimg.SaveOptions{})
if err != nil {
  fmt.Fprintln(os.Stderr, err)
  return
} 

// save the cropped and flipped image
bimg.Write("new.jpg", newImage)
```

After `NewImageTransformation` we now have a `VipsImage` under the hood, not a buffer. The operations `Crop`, `Rotate`, etc. now perform on this `VipsImage` (replacing it in the process). It will not be re-encoded in between. Only when calling `Save` will the image be encoded. Especially when dealing with lossy formats like JPEG, this significantly improves image quality, since it only encodes once (while before it would have encoded and then decoded the JPEG between these stages).

This, in short, is the main new feature of this PR.

---

### Additionally

* `VipsImage` is now ref counted and is registered with the garbage collector for cleanup. So when the Go GC removes the reference, it will also remove its Glib reference. We therefore don't have to cleanup after ourselves all the time (but we *can* call `Close()` to help the GC)
* I added support for saving GIF images (using `magicksave`).
* Background color arrays are now created on the Go side, not on the C side. This shortens the C code and keeps the business logic closer to where we expect it.
* A few VipsVersion checks were wrong and would break in the future. I fixed them.
* I replaced a few cascaded if-statements with switch-statements.
* Determining the filetype is now done using strings instead of sequences of bytes, to increase the readability.

---

### Possible Considerations

I think the `ImageTransformation` could as well replace the `Image` and its fluent interface. This would, however, break the API. If this is desired, we can certainly do that and release it as v2. I am also fine keeping it separate (and/or combine it later).

### CODE REVIEW

**Comment by h2non** [comment]
Apologies for the latency here. I'm happy to embrace these changes, but waiting now to find the proper release fit, as perhaps v2 might include additional enhancements and library redesign that were in the queue for a long while. I don't mind, we will queue up this unless there is a significant demand from the community to ship these improvements.

**Comment by aksdb** [comment]
@h2non Thanks for the feedback. The current implementation is not API breaking (AFAICT). So you could also incorporate these changes now and rename interfaces / cleanup the API later. In this state of the PR the "old" (current) API coexists with the `ImageTransformation` API - but uses this under the hood. So everyone with "old" code can still use it as before. But one *could* switch to the `ImageTransformation` based API if necessary/desired.

**Comment by sethify** [comment]
We could really use the `gif` output.

**Comment by aksdb** [comment]
@sethify feel free to use [our fork](https://github.com/Staffbase/bimg) in the meantime. It now even supports writing any file format supported by ImageMagick (if your libvips is built against it).

**Comment by fi0** [comment]
related to https://github.com/h2non/bimg/issues/364

**Comment by fi0** [comment]
The ImageTransformation is really useful.

**Comment by fi0** [comment]
@aksdb is there a easy way to use your fork? I cannot use it easily because the go.mod is pointing to github.com/h2non/bimg instead of github.com/Staffbase/bimg

**Comment by aksdb** [comment]
> @aksdb is there a easy way to use your fork? I cannot use it easily because the go.mod is pointing to github.com/h2non/bimg instead of github.com/Staffbase/bimg

You can use the `replace` directive:

```
module ...

go 1.16

require (
	...
	github.com/h2non/bimg v1.1.4
	...
)

replace github.com/h2non/bimg => github.com/Staffbase/bimg v1.1.5-0.20210212092339-93cc977fd4cb
```

**Comment by aksdb** [comment]
@h2non What do you think, should I try to split this PR into smaller changes so it gets easier to review? If you are in general short on time (which I assume is pretty likely), this wouldn't help either, right? Would you prefer me to just do a hard fork and keep all my bigger changes there?

**Comment by h2non** [comment]
Hey, sorry for the silence, I'm pretty much off from OSS lately :(

I think the best way to proceed forward would be addressing all these changes in the future `v2`, this will also dissipate much pressure from keeping backward compatibility with existing API contracts, and embracing more flexible, even behavioral changes. The branch is [ready](https://github.com/h2non/bimg/tree/v2).

I'm also happy to give you contributor permissions if you are interested in contributing more often.

**Comment by aksdb** [comment]
> Hey, sorry for the silence, I'm pretty much off from OSS lately :(
> 
> I think the best way to proceed forward would be addressing all these changes in the future `v2`, this will also dissipate much pressure from keeping backward compatibility with existing API contracts, and embracing more flexible, even behavioral changes. The branch is [ready](https://github.com/h2non/bimg/tree/v2).
> 
> I'm also happy to give you contributor permissions if you are interested in contributing more often.

@h2non Thanks for your feedback! If that is fine by you, I would be willing to do that. So I would keep v1 untouched, and refactor my changes even more radically, replacing the old API with it. All as part of v2. Maybe I can also incorporate a few of the other open PRs into that.

So in short: if you trust me enough to do a good job, I would be glad to become a contributor :)

**Comment by h2non** [comment]
@aksdb access granted! Feel free to start iterating in the `v2` branch, but with no pressure, the branch will be considered unstable until everyone involved is comfortable going beta or GA. 

I will try to sporadically provide feedback when possible but feel free to take the leadership on pretty much everything ;)

**Comment by aksdb** [comment]
This is now being incorporated into an upcoming (no release date yet!) v2.

If you want to give it a shot already: `go get -u github.com/h2non/bimg/v2@v2-dev`. The API is not stable yet, obviously.

**Pull request closed without merging**
