### PR TITLE
Adds AVIF support

### LINKED ISSUE #353: Status of AVIF support
Why:

[AVIF](https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4?gi=dc3923b0ca9a) (AV1 Image File Format) is a new image format based on the AV1 video codec.
It supports both lossless and lossy compression and saves up to 50% space
at the same quality compared to JPG.

libvips already support AVIF format https://github.com/libvips/libvips/issues/1364
Is there any way to make AVIF work as of yet or is there is any plan to support in near future

### PR DESCRIPTION
**Pull request by LarsFronius**
* This adds a new type `AVIF` to the supported type list if libvips >= 8.9.0 is installed.
 * Calls libheif through libvips with the AV1 compression set to save AVIF images.

This should fix #353.

### CODE REVIEW

**Comment by LarsFronius** [comment]
We'll perhaps need a newer libheif in the travis CI image. We currently install 1.3.2 through upstream packages, but AVIF support only landed in 1.7.0. I'll have a look if we can compile from source.

**Comment by LarsFronius** [comment]
Test is slow but passing for now. Looks like the libaom en-/decoder is easiest to install for us in CI but a little on the slow side in terms of encoding performance.

There's also the option to use https://code.videolan.org/videolan/dav1d/ as decoder and https://github.com/xiph/rav1e as encoder with libheif. Both have more dependencies and would involve more changes as we'd need to compile them from source it seems.

**Comment by h2non** [comment]
Thanks for the PR! Is this ready?

**Comment by LarsFronius** [comment]
Good to go from my end! 👍

**Comment by akmittal** [comment]
Tried making it work, Getting following error

`heifsave: Unsupported compression`

**Comment by LarsFronius** [comment]
That is the error libheif returns if it isn’t compiled with a AVIF encoder or decoder. Can you try recompiling a recent libheif from source with the rav1e or libaom encoder? I think that should make the error disappear.

I am on the go right now, but if it helps can also supply a container image that works - it works inside the travis CI tests of this PR too btw, where I install libaom and compile libheif from source.

**Comment by akmittal** [comment]
Got it to work by compiling. 
I think this step also should be added in readme to install.
I see 1 issue though. `.Metadata()` method does not return valid info for me.

**Comment by LarsFronius** [comment]
First of all: Glad to hear you got AVIF processing working!
Hmm, to be honest: I have not tested the Metadata function. I'll have a go at it sometime this week!

**Comment by akmittal** [comment]
The latest updates work and Metadata is working fine. It was somewhat of effort to make it work with libheif. I think this step should be added un readme or we should wait for libheif release with avif support to release.

**Comment by LarsFronius** [comment]
Awesome - can you review the sections I added to the README? Mostly only referring to the documentation on the libheif side - no need to duplicate the information in my opinion.

**Comment by akmittal** [comment]
This looks good, 

Although I have a question. https://github.com/strukturag/libheif/releases mentions that they support avif from version 1.8.0. So why we need to compile libheif for this?

**Comment by LarsFronius** [comment]
AVIF support has been in `libheif` from 1.7.0 on:
 * In 1.7.0 reading and writing via `libaom` was added.
 * In 1.8.0 encoding via `rav1e` was added.
 * In 1.9.0 encoding via `dav1d` was added.

Any one of these are libraries need to be present for `libheif`, so that `libheif` can be compiled supporting them - otherwise `libheif` throws the "heifsave: Unsupported compression" error.

For now `libvips` developers have made the choice to encode/decode AVIF via `libheif` - there have been discussions to directly integrate with an AVIF en- or decoder, e.g. `libavif`, but that apparently has been dropped. https://github.com/libvips/libvips/issues/1570

So for now the of `libheif` with one of the three aforementioned AVIF encoders/decoders needs to be made available for `libvips` for it to encode or decode AVIF.

**Comment by LarsFronius** [comment]
Hi, is anything still needed to get this merged?

**Comment by h2non** [comment]
Thanks for the nice work done, and apologies for the latency, OSS is not nowadays something I can spend much time on, unfortunately.

**Comment by LarsFronius** [comment]
Cheers @h2non, absolutely understandable and relatable 👍 
Thanks again for creating and sharing this great library!

**Pull request merged**
