### PR TITLE
Test cases for the EXIF autorotate

### PR DESCRIPTION
**Pull request by greut**
Kudos to
https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

Related to #181

### CODE REVIEW

**Comment by greut** [comment]
@h2non this PR clearly fixes the EXIF cases 5 and 7.

**Comment by greut** [comment]
master

autorotate-master

this branch

autorotate-after

**Comment by h2non** [comment]
Thanks for the nice work here. I'm currently traveling and pretty much offline, but I will review this next week.

**Comment by h2non** [comment]
Nice job! Thanks.

**Pull request merged**
