### PR TITLE
TIFF save

### PR DESCRIPTION
**Pull request by greut**
This aims at adding a 8.5 feature to save as tiff.

I'm not super happy with the bits touching the C code. Any suggestions?

This PR includes #123

### CODE REVIEW

**Comment by greut** [comment]
I'll add that the test checks that saving to a TIFF works for libvips 8.5+

**Comment by greut** [comment]
### libvips 8.4
```
=== RUN   TestVipsSaveTiff
--- SKIP: TestVipsSaveTiff (0.00s)
	vips_test.go:50: Format "tiff" is not supported
```

### libvips master
```
=== RUN   TestVipsSaveTiff
--- PASS: TestVipsSaveTiff (0.03s)
```

**Comment by h2non** [comment]
Thank you. 

PS: feel free to ping me next time if I'm taking too long to review a PR.

**Comment by greut** [comment]
@h2non no worries. Thanks for the merge.

**Pull request merged**
