### PR TITLE
Update libvips-8.5.7

### PR DESCRIPTION
**Pull request by greut**
Test bimg against the latest libvips versions.

### CODE REVIEW

**Comment by h2non** [comment]
We should want to add the alpha version as allowed failure in Travis, don't you think?

**Comment by greut** [comment]
Do you see anything from the changelog that could break? `FORCE` ?
 https://github.com/jcupitt/libvips/blob/master/ChangeLog

**Comment by greut** [comment]
@h2non I've created a separate branch with the alpha release. I'll investigate if any new feature might be useful.

**Comment by h2non** [comment]
@greut please, let me know when I should take a look. Thanks!

**Pull request closed without merging**
