### PR TITLE
Added Progressive JPEG output.

### PR DESCRIPTION
**Pull request by bfitzsimmons**

### CODE REVIEW

**Comment by chreble** [comment]
Nice addition

**Comment by bfitzsimmons** [comment]
Thanks, Christophe.

**Comment by h2non** [comment]
Thank you for the PR!

I made several minor refactors in order to fix an issue with the `interlace` option, since it's a `gboolean` (from glib) type instead of `int`:
```
GLib-GObject-WARNING **: value "TRUE" of type 'gboolean' is invalid or out of range for property 'interlace' of type 'gboolean'
```

I've just released a fresh tag with this feature. Upgrade `bimg` via:
```
go get -u gopkg.in/h2non/bimg.v0
```

**Comment by bfitzsimmons** [comment]
That's great!  I'll update later today. 

Thanks, Tomás!

**Comment by h2non** [comment]
Note that interlaced images will generate negative memory side effects.

According to `libvips` documentation:
```
If interlace is set, the jpeg files will be interlaced (progressive jpeg, in jpg parlance). These files may be better for display over a slow network conection, but need much more memory to encode and decode.
```

And for PNG images:
```
Set interlace to TRUE to interlace the image with ADAM7 interlacing. Beware than an interlaced PNG can be up to 7 times slower to write than a non-interlaced image.
```

I highly recommend to use it only for certain scenarios where the performance is not a premise.

**Comment by bfitzsimmons** [comment]
I'll definitely keep that in mind. Thanks again.

**Pull request merged**
