### PR TITLE
Adding GIF, PDF and SVG support (libvips 8.3)

### PR DESCRIPTION
**Pull request by greut**
Heya, after a long pause, I'm back at it and it seems that libvips now support reading GIF and PDF.

What do you think of this?

Cheers,

source of the gif: http://media.photobucket.com/user/jacobseric/media/publicdomain.gif.html

Issue:
- [x] libvips requires a version of poppler that isn't present into travis to be compiled with pdf support

### CODE REVIEW

**Comment by h2non** [comment]
Thanks! Will take a look asap. 
In the meantime, can you fix the CI build? Looks like shared libraries for GIF/SVG processing were not linked.

**Comment by h2non** [comment]
I don't know about PDF, but GIF/SVG bindings should be easily supported in TravisCI.

**Comment by greut** [comment]
@h2non this is close. I tried to build something along the line of `VIPS_MAGICK_SUPPORT` but didn't find any suitable `#define`. Any clue?

**Comment by greut** [comment]
That change made in may is no yet released... https://github.com/jcupitt/libvips/commit/bec6b174c99bb8121318834b79618cf948447ff6

**Comment by greut** [comment]
@h2non w00t!

**Comment by h2non** [comment]
Update: I'm with limited connectivity these weeks, but once I have time I will test and review this in detail. Thanks!

I assume that only recent versions of libvips support GIF/SVG bindings, is that right?

**Comment by greut** [comment]
@h2non indeed, only 8.3 has it https://github.com/jcupitt/libvips/blob/master/ChangeLog#L65

**Comment by h2non** [comment]
Merged! Thank you for the great job!

**Comment by greut** [comment]
@h2non cool! You're welcome.

**Comment by h2non** [comment]
This feature is now officially supported in `bimg@1.0.3` with further improvements.
See: https://github.com/h2non/bimg/pull/110

**Pull request merged**
